name: Release Drafter

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  update_release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}